const en = {
  header: {
    upload: "Upload",
    dark: "Dark mode",
    light: "Light mode",
    login: "SIGN IN",
    signup: "SIGN UP",
    logout: "Log out",
    tools: "General tools",
    videosSaved: "Videos Saved",
    settingsConfig: "Settings Configuration",
    myData: "My Data",
    notifications: "Notifications & messages",
    helpSupport: "Help & Support",
  },
  auth: {
    login: {
      subtitle: "Sign in to enjoy all the content.",
      email: "Email",
      emailPlaceholder: "Your email",
      password: "Password",
      passwordPlaceholder: "Your password",
      signingIn: "SIGNING IN...",
      signIn: "SIGN IN",
      google: "Continue with Google",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
      forgotPassword: "Forgot your password?",
      recover: "Recover",
      verificationSubtitle: "We sent a 6-digit code to",
      verificationCode: "Verification code",
      verifying: "VERIFYING...",
      verifyAccount: "VERIFY ACCOUNT",
      resendCode: "Resend code",
      codeSent: "Code sent to your email",
      errors: {
        loginFailed: "Login failed",
        invalidCode: "Invalid code",
        resendFailed: "Failed to resend code",
        connection: "Connection error",
      },
    },
    signup: {
      subtitle: "Create your account and enjoy all the content.",
      email: "Email",
      emailPlaceholder: "Your email",
      password: "Password",
      passwordPlaceholder: "Min. 8 chars, 1 uppercase & 1 number",
      repeatPassword: "Repeat password",
      repeatPasswordPlaceholder: "Repeat your password",
      creatingAccount: "CREATING ACCOUNT...",
      createAccount: "CREATE ACCOUNT",
      google: "Continue with Google",
      hasAccount: "Already have an account?",
      signIn: "Sign in",
      verificationSubtitle: "We sent a 6-digit code to",
      verificationCode: "Verification code",
      verifying: "VERIFYING...",
      verifyAccount: "VERIFY ACCOUNT",
      resendCode: "Resend code",
      codeSent: "Code sent to your email",
      errors: {
        passwordMismatch: "Passwords do not match",
        registrationFailed: "Registration failed",
        invalidCode: "Invalid code",
        resendFailed: "Failed to resend code",
        connection: "Connection error",
      },
    },
  },
  orientacion: {
    hetero: "Hetero",
    gay: "Gay",
    lesbian: "Lesbian",
    bisexual: "Bisexual",
    trans: "Trans",
    todos: "All",
  },
  nav: {
    home: "Home",
    videos: "Videos",
    categories: "Categories",
    tags: "Tags",
    albums: "Albums",
    models: "Models",
    theporndude: "Theporndude",
    livesex: "LIVE SEX",
    telegram: "Telegram",
    premium: "Premium",
  },
  navDropdown: {
    videos: {
      latest: "Latest",
      mostViewed: "Most Viewed",
      topRated: "Top Rated",
    },
    allCategories: "All Categories",
    allTags: "All Tags",
    albums: {
      topRated: "Top Rated",
      mostViewed: "Most Viewed",
    },
    allModels: "All Models",
  },
  footer: {
    col0: {
      title: "Information",
      links: ["Terms & Conditions", "Privacy Policy", "DMCA", "18 USC 2257"],
    },
    col1: {
      accent: "Work",
      rest: "With Us",
      links: ["Content Partners", "Advertise", "Webmasters", "Model Program"],
    },
    col2: {
      accent: "Support",
      rest: "and Help",
      links: ["Contact Support", "Sitemap"],
    },
    col3: {
      title: "Friends",
      links: ["Porntrex", "Camwhoresbay", "Javwhores", "BongaCams"],
    },
    copy: "2025 WhoresHub.com All rights reserved.",
    spot: {
      title: "Welcome To WhoresHub",
      text: "WhoresHub.com is a large collection of the newest high-quality porn videos in high resolution. Enjoy our user-friendly platform to find and enjoy the best sex videos across different categories on any of your devices. We constantly update each category with the latest HD porn videos to meet the diverse taste of our visitors.",
    },
  },
  home: {
    sections: {
      recently_added: { lead: "Free HD Porn Videos", rest: "and Movies" },
      top_rated: { lead: "Top", rest: "Rated Videos" },
      most_favourited: { lead: "Most", rest: "Favourited Videos" },
    },
    sortLabels: {
      topRated: "Top Rated",
      mostFavourited: "Most Favourited",
      mostViewed: "Most Viewed",
      alphabetically: "Alphabetically",
      mostVideos: "Most Videos",
      heterosexual: "Heterosexual",
      gay: "Gay",
      transsexual: "Transsexual",
    },
    tagFilter: {
      videos: "Videos",
      albums: "Albums",
    },
    categories: {
      lead: "Most",
      rest: "Viewed Categories",
    },
    pages: {
      latestUpdates: { lead: "Latest Updates", rest: "Videos" },
      topRatedVideos: { lead: "Top", rest: "Rated Videos" },
      mostViewed: { lead: "Most Viewed", rest: "Videos" },
      categories: { lead: "Top", rest: "Rated Porn Categories" },
      tags: { lead: "Tags", rest: "Videos" },
      tagged: { lead: "Top", rest: "Rated Videos Tagged with" },
    },
  },
  pagination: {
    previous: "Previous",
    next: "Next",
    jumpTo: "Jump to:",
    ok: "Ok",
  },
  sidebar: {
    sortBy: "Sort by",
    videoQuality: "Video Quality",
    videoType: "Video Type",
    freeVideos: "Free videos",
    premiumVideos: "Premium videos",
    all: "All",
    hd: "HD",
    popularTags: "Popular Tags",
    popularCategories: "Popular Categories",
    trendingSearches: "Trending Searches",
  },
  profile: {
    myAccount: "My Account",
    personalInfo: "Personal Information",
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    memberSince: "Member since",
    orientation: "Orientation",
    password: "Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    changePassword: "Change Password",
    saveChanges: "Save Changes",
    saved: "Saved",
    saving: "Saving...",
    passwordChanged: "Password changed successfully",
    logout: "Log out",
    deleteAccount: "Delete Account",
    confirmDelete: "Are you sure you want to delete your account? This action cannot be undone.",
    cancel: "Cancel",
    delete: "Delete",
    profileUpdated: "Profile updated successfully",
    uploadAvatar: "Upload avatar",
    notLoggedIn: "You are not logged in",
    loginToAccess: "Please sign in to access your profile",
    settingsConfig: "Settings Configuration",
    preferences: "Preferences",
    language: "Language",
    privateBrowsing: "Private browsing",
    privateBrowsingDesc: "Hide your activity from other users",
    contentHistory: "Content history",
    contentHistoryDesc: "Save your browsing history",
    notifications: "Notifications & Messages",
    emailNotif: "Email notifications",
    emailNotifDesc: "Receive updates via email",
    pushNotif: "Push notifications",
    pushNotifDesc: "Receive push notifications on your device",
    messageNotif: "Messages from users",
    messageNotifDesc: "Allow other users to send you messages",
    savedVideos: "Videos Saved",
    noSavedVideos: "You haven't saved any videos yet",
    noSavedVideosDesc: "Videos you save will appear here",
    exploreVideos: "Explore videos",
  },
  upload: {
    video: "Video",
    album: "Album",
    model: "Model",
    photos: "Photos",
    dropVideos: "Drag & drop videos here or click to browse",
    dropPhotos: "Drag & drop photos here or click to browse",
    videoFormats: "MP4, WebM, AVI, MKV, MOV",
    photoFormats: "JPEG, PNG, WebP, GIF, BMP",
    title: "Title",
    titlePlaceholder: "Enter a title for your upload",
    description: "Description",
    descriptionPlaceholder: "Describe your content",
    category: "Category",
    categoryPlaceholder: "Select category",
    tags: "Tags",
    uploading: "UPLOADING...",
    upload: "Upload",
    selectedFile: "Selected file",
    albumName: "Album Name",
    albumNamePlaceholder: "Enter a name for your album",
    coverImage: "Cover Image",
    clickToUpload: "Click to upload",
    photosSelected: "photos selected",
    models: "Models",
    modelsPlaceholder: "Comma separated model names",
    createAlbum: "Create Album",
    modelName: "Model Name",
    age: "Age",
    country: "Country",
    city: "City",
    height: "Height",
    weight: "Weight",
    bio: "Bio",
    bioPlaceholder: "Describe the model",
    avatar: "Avatar",
    socialNetworks: "Social Networks",
    createModel: "Create Model",
    selectVideoHint: "Select a video and enter a title",
    albumRequiredHint: "Enter a name and add at least one photo",
    modelRequiredHint: "Enter the model name",
  },
}

export default en
