const es = {
  header: {
    upload: "Subir",
    dark: "Modo oscuro",
    light: "Modo claro",
    login: "INICIAR SESIÓN",
    signup: "CREAR CUENTA",
    logout: "Cerrar sesión",
    tools: "Herramientas generales",
    videosSaved: "Videos Guardados",
    settingsConfig: "Configuración de Ajustes",
    myData: "Mis Datos",
    notifications: "Notificaciones y mensajes",
    helpSupport: "Ayuda y Soporte",
  },
  auth: {
    login: {
      subtitle: "Inicia sesión para disfrutar de todo el contenido.",
      email: "Correo electrónico",
      emailPlaceholder: "Tu correo electrónico",
      password: "Contraseña",
      passwordPlaceholder: "Tu contraseña",
      signingIn: "INICIANDO...",
      signIn: "INICIAR SESIÓN",
      google: "Continuar con Google",
      noAccount: "¿No tienes cuenta?",
      createAccount: "Crear cuenta",
      forgotPassword: "¿Olvidaste tu contraseña?",
      recover: "Recuperar",
      verificationSubtitle: "Te enviamos un código de 6 dígitos a",
      verificationCode: "Código de verificación",
      verifying: "VERIFICANDO...",
      verifyAccount: "VERIFICAR CUENTA",
      resendCode: "Reenviar código",
      codeSent: "Código enviado a tu correo",
      errors: {
        loginFailed: "Error al iniciar sesión",
        invalidCode: "Código inválido",
        resendFailed: "Error al reenviar código",
        connection: "Error de conexión con el servidor",
      },
    },
    signup: {
      subtitle: "Crea tu cuenta y disfruta de todo el contenido.",
      email: "Correo electrónico",
      emailPlaceholder: "Tu correo electrónico",
      password: "Contraseña",
      passwordPlaceholder: "Mín. 8 caracteres, 1 mayúscula y 1 número",
      repeatPassword: "Repetir contraseña",
      repeatPasswordPlaceholder: "Repite tu contraseña",
      creatingAccount: "CREANDO CUENTA...",
      createAccount: "CREAR CUENTA",
      google: "Continuar con Google",
      hasAccount: "¿Ya tienes cuenta?",
      signIn: "Iniciar sesión",
      verificationSubtitle: "Te enviamos un código de 6 dígitos a",
      verificationCode: "Código de verificación",
      verifying: "VERIFICANDO...",
      verifyAccount: "VERIFICAR CUENTA",
      resendCode: "Reenviar código",
      codeSent: "Código enviado a tu correo",
      errors: {
        passwordMismatch: "Las contraseñas no coinciden",
        registrationFailed: "Error al registrarse",
        invalidCode: "Código inválido",
        resendFailed: "Error al reenviar código",
        connection: "Error de conexión con el servidor",
      },
    },
  },
  orientacion: {
    hetero: "Hetero",
    gay: "Gay",
    lesbian: "Lesbian",
    bisexual: "Bisexual",
    trans: "Trans",
    todos: "Todos",
  },
  nav: {
    home: "Inicio",
    videos: "Videos",
    categories: "Categorías",
    tags: "Etiquetas",
    albums: "Álbumes",
    models: "Modelos",
    theporndude: "Theporndude",
    livesex: "SEXO EN VIVO",
    telegram: "Telegram",
    premium: "Premium",
  },
  navDropdown: {
    videos: {
      latest: "Últimos",
      mostViewed: "Más Vistos",
      topRated: "Mejor Valorados",
    },
    allCategories: "Todas las Categorías",
    allTags: "Todas las Etiquetas",
    albums: {
      topRated: "Mejor Valorados",
      mostViewed: "Más Vistos",
    },
    allModels: "Todos los Modelos",
  },
  footer: {
    col0: {
      title: "Información",
      links: ["Términos y Condiciones", "Política de Privacidad", "DMCA", "18 USC 2257"],
    },
    col1: {
      accent: "Trabaja",
      rest: "Con Nosotros",
      links: ["Socios de Contenido", "Anunciarse", "Webmasters", "Programa de Modelos"],
    },
    col2: {
      accent: "Soporte",
      rest: "y Ayuda",
      links: ["Contactar Soporte", "Mapa del Sitio"],
    },
    col3: {
      title: "Amigos",
      links: ["Porntrex", "Camwhoresbay", "Javwhores", "BongaCams"],
    },
    copy: "2025 WhoresHub.com Todos los derechos reservados.",
    spot: {
      title: "Bienvenido a WhoresHub",
      text: "WhoresHub.com es una gran colección de los videos pornográficos de alta calidad más nuevos en alta resolución. Disfruta de nuestra plataforma fácil de usar para encontrar y disfrutar de los mejores videos de sexo en diferentes categorías desde cualquier dispositivo. Actualizamos constantemente cada categoría con los últimos videos HD para satisfacer los diversos gustos de nuestros visitantes.",
    },
  },
  home: {
    sections: {
      recently_added: { lead: "Videos Porno HD", rest: "Gratis y Películas" },
      top_rated: { lead: "Los Más", rest: "Valorados" },
      most_favourited: { lead: "Los Más", rest: "Favoritos" },
    },
    sortLabels: {
      topRated: "Mejor Valorados",
      mostFavourited: "Más Favoritos",
      mostViewed: "Más Vistos",
      alphabetically: "Alfabéticamente",
      mostVideos: "Más Videos",
      heterosexual: "Heterosexual",
      gay: "Gay",
      transsexual: "Transexual",
    },
    tagFilter: {
      videos: "Videos",
      albums: "Álbumes",
    },
    categories: {
      lead: "Categorías",
      rest: "Más Vistas",
    },
    pages: {
      latestUpdates: { lead: "Últimas", rest: "Actualizaciones" },
      topRatedVideos: { lead: "Los Más", rest: "Valorados" },
      mostViewed: { lead: "Más", rest: "Vistos" },
      categories: { lead: "Mejor", rest: "Valoradas Categorías Pornográficas" },
      tags: { lead: "Etiquetas", rest: "Videos" },
      tagged: { lead: "Los Más", rest: "Valorados Etiquetados con" },
    },
  },
  pagination: {
    previous: "Anterior",
    next: "Siguiente",
    jumpTo: "Ir a:",
    ok: "Ir",
  },
  sidebar: {
    sortBy: "Ordenar por",
    videoQuality: "Calidad de Video",
    videoType: "Tipo de Video",
    freeVideos: "Videos Gratis",
    premiumVideos: "Videos Premium",
    all: "Todos",
    hd: "HD",
    popularTags: "Etiquetas Populares",
    popularCategories: "Categorías Populares",
    trendingSearches: "Búsquedas Populares",
  },
  profile: {
    myAccount: "Mi Cuenta",
    personalInfo: "Información Personal",
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    email: "Correo Electrónico",
    memberSince: "Miembro desde",
    orientation: "Orientación",
    password: "Contraseña",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    changePassword: "Cambiar Contraseña",
    saveChanges: "Guardar Cambios",
    saved: "Guardado",
    saving: "Guardando...",
    passwordChanged: "Contraseña cambiada exitosamente",
    logout: "Cerrar Sesión",
    deleteAccount: "Eliminar Cuenta",
    confirmDelete: "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    delete: "Eliminar",
    profileUpdated: "Perfil actualizado exitosamente",
    uploadAvatar: "Subir avatar",
    notLoggedIn: "No has iniciado sesión",
    loginToAccess: "Inicia sesión para acceder a tu perfil",
    settingsConfig: "Configuración de Ajustes",
    preferences: "Preferencias",
    language: "Idioma",
    privateBrowsing: "Navegación privada",
    privateBrowsingDesc: "Oculta tu actividad de otros usuarios",
    contentHistory: "Historial de contenido",
    contentHistoryDesc: "Guarda tu historial de navegación",
    notifications: "Notificaciones y Mensajes",
    emailNotif: "Notificaciones por correo",
    emailNotifDesc: "Recibe actualizaciones por correo electrónico",
    pushNotif: "Notificaciones push",
    pushNotifDesc: "Recibe notificaciones push en tu dispositivo",
    messageNotif: "Mensajes de usuarios",
    messageNotifDesc: "Permite que otros usuarios te envíen mensajes",
    savedVideos: "Videos Guardados",
    noSavedVideos: "No has guardado ningún video aún",
    noSavedVideosDesc: "Los videos que guardes aparecerán aquí",
    exploreVideos: "Explorar videos",
  },
  upload: {
    video: "Video",
    album: "Álbum",
    model: "Modelo",
    photos: "Fotos",
    dropVideos: "Arrastra videos aquí o haz clic para buscar",
    dropPhotos: "Arrastra fotos aquí o haz clic para buscar",
    videoFormats: "MP4, WebM, AVI, MKV, MOV",
    photoFormats: "JPEG, PNG, WebP, GIF, BMP",
    title: "Título",
    titlePlaceholder: "Ingresa un título para tu subida",
    description: "Descripción",
    descriptionPlaceholder: "Describe tu contenido",
    category: "Categoría",
    categoryPlaceholder: "Selecciona categoría",
    tags: "Etiquetas",
    uploading: "SUBIIENDO...",
    upload: "Subir",
    selectedFile: "Archivo seleccionado",
    albumName: "Nombre del Álbum",
    albumNamePlaceholder: "Ingresa un nombre para tu álbum",
    coverImage: "Imagen de Portada",
    clickToUpload: "Haz clic para subir",
    photosSelected: "fotos seleccionadas",
    models: "Modelos",
    modelsPlaceholder: "Nombres de modelos separados por comas",
    createAlbum: "Crear Álbum",
    modelName: "Nombre del Modelo",
    age: "Edad",
    country: "País",
    city: "Ciudad",
    height: "Altura",
    weight: "Peso",
    bio: "Biografía",
    bioPlaceholder: "Describe al modelo",
    avatar: "Avatar",
    socialNetworks: "Redes Sociales",
    createModel: "Crear Modelo",
    selectVideoHint: "Selecciona un video y escribe un título",
    albumRequiredHint: "Ingresa un nombre y agrega al menos una foto",
    modelRequiredHint: "Ingresa el nombre del modelo",
  },
}

export default es
